# Add application configuration variables here
#

#DEV
JPEGGER_WSDL_URL: "http://personalfinancesystem.com/jpeggertrigger.dll/wsdl/IJpeggerTrigger"

### End jpegger  database information ###

JPEGGER_SERVICE: "71.41.52.58"


### Start sidekiq information ###
SIDEKIQ_USERNAME: "sidekiq"
SIDEKIQ_PASSWORD: "sidekiq"
### End sidekiq information ###

### Start mailer information ###
GMAIL_USERNAME: "info@scrapyarddog.com"
GMAIL_PASSWORD: "Roost3r2017!"
### Start mailer information ###

SECRET_KEY_BASE: "a3dace48f6422e674e4cbe4a2e65b44eaa9f601f19b9bf059ed836a1a84bb5c4e0f9491d31920ac6ef49c37880826ed3de4aed49cddd6989109d7c765e542ce1"

GOOGLE_MAPS_API_KEY: "AIzaSyACWbJtAmobXmtZWdZmWzUo7ssMY-BEQAg"